# Generated by Django 5.0.6 on 2024-07-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="corpus",
            field=models.TextField(blank=True, null=True),
        ),
    ]
